export { default as Header } from './Header/Header'
export { default as Footer } from './Footer/Footer'
export { default as Clients } from './Clients/Clients'
export { default as Us } from './Us/Us'
export { default as Gallery } from './Gallery/Gallery'
export { default as Services } from './Services/Services'
export { default as Hero } from './Hero/Hero'
