export { default as Logo } from './Logo/Logo'
export { default as NavBar } from './NavBar/NavBar'
export { default as MobileMenu } from './MobileMenu/MobileMenu'
export { default as Contact } from './Contact/Contact'
export { default as Copyright } from './Copyright/Copyright'
export { default as Menu } from './Menu/Menu'
export { default as Socials } from './Socials/Socials'
export { default as HeroTitle } from './Titles/HeroTitle'
